name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    uses: mhils/workflows/.github/workflows/rust-test.yml@main

  deploy:
    uses: mhils/workflows/.github/workflows/rust-deploy.yml@main
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    secrets:
      cargo-registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}